name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NR_LICENSE_KEY }}
        run: docker build . --file Dockerfile.alpine --tag azumax/webapp_php:alpine --build-arg COMMIT_SHA=`git rev-parse HEAD` --build-arg NEW_RELIC_AGENT_VERSION=9.18.1.303 --build-arg NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY} --build-arg NEW_RELIC_APPNAME=webapp; docker push azumax/webapp_php:alpine
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: restart
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: -n sock-shop-nr rollout restart deploy webapp-php
      - name: Deploy marking
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NR_KEY }}
        run: curl -X POST "https://api.newrelic.com/v2/applications/1043147034/deployments.json" -H "Api-Key:$NEW_RELIC_API_KEY" -H "Content-Type:application/json" -d '{"deployment":{"revision":"'`git rev-parse HEAD`'","user":"Auto Deploy","timestamp":"'`date +'%Y-%m-%dT%H:%M:%S'Z`'"}}'
